//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.0.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("[\r\n       {\r\n\t\t\"id\": 0,\r\n\t\t\"name\": \"D\",\r\n\t\t\"value\": \"D:\\\\Torrent2\\\\Movies\"\r\n\t}, \r" +
            "\n        {\r\n\t\t\"id\": 1,\r\n\t\t\"name\": \"K\",\r\n\t\t\"value\": \"K:\\\\uTorrent\\\\Movies\"\r\n\t}\r\n]" +
            "")]
        public string Disks {
            get {
                return ((string)(this["Disks"]));
            }
        }
    }
}
