//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_User
    {
        public int Id { get; set; }
        public string user_id { get; set; }
        public string user_action { get; set; }
        public string user_type { get; set; }
        public string user_movie { get; set; }
        public Nullable<System.DateTime> user_datetime { get; set; }
    }
}
