//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class History_API
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> api_datetime { get; set; }
        public string api_action { get; set; }
        public string api_type { get; set; }
    }
}
