//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDBSQLEntities : DbContext
    {
        public MDBSQLEntities()
            : base("name=MDBSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MovieData> MovieDatas { get; set; }
        public virtual DbSet<MovieInfo> MovieInfoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
