//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MDBSQLEntities : DbContext
    {
        public MDBSQLEntities()
            : base("name=MDBSQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<History_API> History_API { get; set; }
        public virtual DbSet<History_User> History_User { get; set; }
        public virtual DbSet<Movie_Data> Movie_Data { get; set; }
        public virtual DbSet<Movie_Info> Movie_Info { get; set; }
        public virtual DbSet<Session_Play> Session_Play { get; set; }
        public virtual DbSet<User_Groups> User_Groups { get; set; }
        public virtual DbSet<User_Info> User_Info { get; set; }
    }
}
