//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class MovieData
    {
        public int Id { get; set; }
        public string movie_name { get; set; }
        public string movie_ext { get; set; }
        public string movie_guid { get; set; }
        public string movie_folder { get; set; }
    
        public virtual MovieInfo MovieInfo { get; set; }
    }
}
