//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session_Guest
    {
        public int Id { get; set; }
        public string movie_id { get; set; }
        public string session_id { get; set; }
        public Nullable<System.DateTime> session_date { get; set; }
    }
}
