//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace api
{
    using System;
    using System.Collections.Generic;
    
    public partial class User_Groups
    {
        public int Id { get; set; }
        public string type { get; set; }
        public string name { get; set; }
        public string access { get; set; }
        public string desc { get; set; }
        public bool status { get; set; }
    }
}
